name: landmark-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - pip:
    - opencv-python==4.9.0.80
    - mediapipe==0.10.11